import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const satoshiFont = localFont({
  src: [
    {
      path: "./assets/fonts/Satoshi-Light.woff",
      weight: "300",
      style: "normal",
    },
    {
      path: "./assets/fonts/Satoshi-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/Satoshi-Medium.woff",
      weight: "500",
      style: "normal",
    },
    {
      path: "./assets/fonts/Satoshi-Bold.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./assets/fonts/Satoshi-Black.woff",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${satoshiFont.className} antialiased`}>{children}</body>
    </html>
  );
}
